### ISSUE TITLE
pe分辨率无法通过pecmd调整

### ISSUE THREAD

**Issue by SteveZMTstudios** [EdgelessPE/Edgeless#12]
右下角的彩色显示器无法校准显示器的分辨率（1600x900 30f）新建 分辨率.txt 也无济于事。

**Comment by Cnotech** [comment]
尝试 https://wiki.edgeless.top/v2/faq/resolution.html

**Comment by SteveZMTstudios** [comment]
建议把那个菠萝云链接换掉😅

**Comment by Cnotech** [comment]
> 建议把那个菠萝云链接换掉😅

菠萝云仅对于浙江移动无法连接，据服务器供应商称是由于浙江移动没有到河南联通的接入点，以后会逐步加入多节点负载均衡
