### ISSUE TITLE
网络问题Edgeless_Beta_4.1.0

### ISSUE THREAD

**Issue by cloversky** [EdgelessPE/Edgeless#16]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Maybe it's a hardware incompatible problem?

Yes. I use Edgeless with modern hardware.

### Edgeless Version

Edgeless_Beta_4.1.0

### What about alpha release?

Yes. I have tried the latest alpha release.

### What happened?

![1](https://user-images.githubusercontent.com/60347528/158627528-aca73684-09d6-410a-8ce7-5950e381f471.jpg)
![2](https://user-images.githubusercontent.com/60347528/158627551-779a5692-fb03-4cf2-ac6e-9571d03b2a5d.jpg)

**Comment by Cnotech** [comment]
这个功能不属于 Edgeless “承诺给予的特性”，会随着 WinPE 内核的变动而改变，因此我们不会将其视为一个 bug。对于您来说可能需要保持两个版本同时持有的状态，造成的不便敬请谅解。
