### ISSUE TITLE
[hub]: 是否能在制作启动盘之前，校验下载得到之二进制的完整性？

### ISSUE THREAD

**Issue by Mikotwa** [EdgelessPE/Edgeless#17]
似乎没有看见 Suggestions 的模板，故直接使用空白模板提交了。如有不便，还请见谅。

似乎目前 Hub 在下载制作启动盘所需要的内容时，不会检验相应二进制的完整性。且用户也无法主动检验相应文件的完整性（没有特定文件的 Hash 值）

如果可以的话，作者是否可以在下载站提供相应 ISO 镜像的 Hash 值（如 SHA-1），以便于核验完整性？

**Comment by Cnotech** [comment]
目前的后端和客户端确实没有加入哈希校验这一步骤，未来重构Edgeless Hub时会考虑增加这一功能。
此issue会保持打开状态。

Edgeless_Beta_4.1.0.iso
CRC32: A006455F
MD5: 35887B073DE3FD07FA23A3602BE811EC
SHA-1: D4E74686D0B56698E0069751DF11DAF409DD78E7

**Comment by XiaotianDong** [comment]
这个问题感觉可以直接用aria2的checksum参数去校验？

**Comment by Cnotech** [comment]
服务器那边需要提前计算哈希值然后提供api接口，涉及到后端改造，还挺麻烦的

**Comment by Cnotech** [comment]
此 issue 与 https://github.com/EdgelessPE/Edgeless/issues/14 部分重复，故关闭
