### ISSUE TITLE
关于一些安装到硬盘的建议

### ISSUE THREAD

**Issue by 1216692740** [EdgelessPE/Edgeless#18]
不小心保存了，内容编写中

**Comment by 1216692740** [comment]
这个是我用其他方式安装edgeless到硬盘的过程
第一步，新建一个分区，用来塞boot.sdi和WIM主文件和edgeless文件夹
注意：不分区的话boot.sdi和WIM主文件可以放在一个文件夹中但最好不是edgeless文件夹中（没测过）edgeless文件夹必须放在某盘（指盘符）的根目录
第二步，添加引导，使用Bootice编辑BCD文件，先建一个Win7/8/8.1启动项，在【启动设备】中选择RAMDISK，启动硬盘和启动分区看WIM主文件存在哪里，然后在设备文件处写上【WIM主文件所存放的文件夹】\【WIM主文件名.wim】。然后再点击sdi文件处的默认显示[boot]的按钮，在跳出来的界面选择Disk Partition，然后在下方选好启动硬盘和启动分区（看boot.sdi存到哪里）点确定，然后在sdi文件的右处写上【boot.sdi文件所存放的文件夹】\boot.sdi
注意：在sdi文件处和设备文件处写上的内容一定不要带盘符！！！
第三步，设置引导，在【设置】里勾上检测硬检抽象层和启动到WinPE，保存当前系统设置，保存全局设置。
至此，安装完成

**Comment by 1216692740** [comment]
我是参考FirPE安装到硬盘的过程来安装硬盘。
这个方法可以兼容几乎所有设备（除非Edgeless不支持的设备）

**Comment by Cnotech** [comment]
对于目前市面上在售的电脑来说基本都是使用UEFI引导且默认不启用CMS的，因此这种编辑BCD增加引导的方式不再适合于Edgeless支持的大部分目标机，而修改EFI引导又会十分麻烦且很难使用程序自动完成，在Windows Boot Manager增加启动项则会拖慢Windows的快速启动，因此目前不推荐将Edgeless安装到本地硬盘。

Edgeless自带的安装硬盘版选项原理是替换WinRE启动文件，但是在最近的Win10系统中WinRE的启动文件似乎被移动到别处，更加难以完成替换，之后有计划将此功能从Edgeless中移除，有此类需求的用户可以自行解决这种问题。

**Comment by 1216692740** [comment]
谢谢回复
