### ISSUE TITLE
[kernel]: PE的分辨率始终无法调整

### ISSUE THREAD

**Issue by Duck-Deng** [EdgelessPE/Edgeless#19]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Maybe it's a hardware incompatible problem?

Yes. I use Edgeless with modern hardware.

### Edgeless Version

4.1.0

### What about alpha release?

Yes. I have tried the latest alpha release.

### What happened?

PE的分辨率始终无法调整，无论是使用pecmd还是右下角的彩色显示器图标。我尝试过一个第三方程序[NirCmd](http://www.nirsoft.net/utils/nircmd.html)  ，它有一个命令行调整分辨率的功能，但仍然不起作用（使用后没有任何翻反应，没有报错或其他提示）。更改分辨率.txt也没用，设置的1366x768，但启动后实际上是1360x768.
尝试了Wiki中的[方法](https://wiki.edgeless.top/v2/faq/resolution.html#uefi-%E5%90%AF%E5%8A%A8%E5%90%8E%E5%88%86%E8%BE%A8%E7%8E%87%E8%BF%87%E4%BD%8E) ，但没用。

**Comment by Duck-Deng** [comment]
补充 https://github.com/EdgelessPE/Edgeless/issues/12 的所有方法都试过了

**Comment by Cnotech** [comment]
是使用UEFI引导启动的吗？UEFI引导的时候由于缺失显卡驱动是无法调整分辨率的，已经在Hub配置的相关位置说明。

**Comment by Duck-Deng** [comment]
> 是使用UEFI引导启动的吗？UEFI引导的时候由于缺失显卡驱动是无法调整分辨率的，已经在Hub配置的相关位置说明。

感想，用BIOS启动正常了。那UEFI启动有什么办法修复驱动问题吗？

**Comment by Cnotech** [comment]
在PE内安装一个体积硕大的显卡驱动没有实用意义，而且适配也较为繁琐，不考虑提供官方支持
