### ISSUE TITLE
关于eclipse中编辑器字体问题

### ISSUE THREAD

**Issue by BlazingStellar** [EdgelessPE/Edgeless#22]
在edgeless中，字体全部变成了一种很细的字体，导致代码整体看起来很乱，希望可以处理一下这个问题，这样能写代码就非常棒了，能补图的话我之后会补张图对比

**Comment by Cnotech** [comment]
为了压缩镜像体积，通常pe都会使用精简的字体作为系统显示字体，因此确实有你所述的情况存在。建议修改eclipse插件包的配置，将代码显示使用的字体改为自定义字体。

**Comment by BlazingStellar** [comment]
能不能自己用插件向pe中补充所需的字体呢

**Comment by Cnotech** [comment]
肯定能啊...写个简单脚本就行

**Comment by Cnotech** [comment]
关闭长时间无回复的issue
