### ISSUE TITLE
[website]: 添加自定义驱动wiki页面描述不清晰

### ISSUE THREAD

**Issue by chinanoahli** [EdgelessPE/Edgeless#23]
### What happened?

使用插件包方法的话，插件包模板是需要将`myDrivers`文件夹里面的东西都先删除吗？
DISM++导出的多个驱动可以直接以嵌套目录的方式放到`myDrivers`吗？
还是说必须将ini和相关的sys文件直接放到`myDrivers`里面？
还是说每一个驱动都需要分开单独打包？

这些问题都没有描述清晰

**Comment by Cnotech** [comment]
文档已更新，感谢你的反馈
