### ISSUE TITLE
[kernel]: 在vmware中以iso的方式启动时，无法修改分辨率

### ISSUE THREAD

**Issue by chinanoahli** [EdgelessPE/Edgeless#24]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Maybe it's a hardware incompatible problem?

Yes. I use Edgeless with modern hardware.

### Edgeless Version

4.1.0

### What about alpha release?

Yes. I have tried the latest alpha release.

### What happened?

我已经将最新的相关驱动从普通win10虚拟机中提取出来，并注入到edgeless的boot wim中，但启动后，不论是通过pecmd还是通过显示设置里面的分辨率尝试修改显示分辨率都无效。

请问要如何才能在vmware中以任意分辨率启动edgeless？
或者有没有办法让分辨率调整正常工作？

**Comment by Cnotech** [comment]
vmware不需要改驱动啥的，调整分辨率功能可以使用的啊。你可以试试切换到Legacy引导启动。

**Comment by chinanoahli** [comment]
似乎并不是十分稳定，1920x1080这一个分辨率经常不可用
可用的只有1152x864（最大），已经设置为Legacy引导启动

**Comment by chinanoahli** [comment]
具体表现请看视频
链接：https://pan.baidu.com/s/1KD_46YX8Eg5X5nQrp6-nEQ?pwd=l61l 
提取码：l61l 
因为超过了github 10MB限制，所以只能网盘了

**Comment by Cnotech** [comment]
有没有按照[文档](https://wiki.edgeless.top/v2/playground/config.html#启动时使用自定义分辨率-禁止自动调节分辨率)放置自定义分辨率文件？

![image](https://user-images.githubusercontent.com/53827731/177040470-6542ff35-7695-49ac-b756-a9b1d1b2c092.png)

**Comment by chinanoahli** [comment]
> 有没有按照[文档](https://wiki.edgeless.top/v2/playground/config.html#%E5%90%AF%E5%8A%A8%E6%97%B6%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%86%E8%BE%A8%E7%8E%87-%E7%A6%81%E6%AD%A2%E8%87%AA%E5%8A%A8%E8%B0%83%E8%8A%82%E5%88%86%E8%BE%A8%E7%8E%87)放置自定义分辨率文件？
> 
> ![image](https://user-images.githubusercontent.com/53827731/177040470-6542ff35-7695-49ac-b756-a9b1d1b2c092.png)

不起效，仍然以原始分辨率启动

**Comment by Cnotech** [comment]
看了一下你的视频，你的虚拟机卡顿似乎比较严重（显示100%之后正常情况下是会在2s内淡出然后进入桌面的），甚至在修改分辨率的时候出现了渲染错误，可能因为某些原因导致了虚拟机异常（例如实体机的配置不够等）。

可以试一下实体机Legacy启动有没有这个问题，我本地使用的VMWare Workstation没有出现这个问题，这边没有办法复现😢

**Comment by chinanoahli** [comment]
主要是我用实体机的话，就没有意义了，我的用途是虚拟机跑一个cctalk，在虚拟机外录屏购买过的课程
cctalk会检测是否有录屏软件同时在运行，如果有，则不会播放课程，并提示有录屏行为

经过测试后发现，vmware下需要驱动+配置文件的方式，就可以开机正常自动调整到目标分辨率
[VMwareDriver.zip](https://github.com/EdgelessPE/Edgeless/files/9034842/VMwareDriver.zip)

我自己打包了驱动，再加上配置文件，就可以开机自动设置分辨率为1920x1080了
本文件仅包含驱动，不包含vmware tools，github不支持7z，可能需要自行转换一下格式

**Comment by chinanoahli** [comment]
同样的方法对VirtualBox无效，即使驱动已经正确加载，但分辨率仍然无法设置为1920x1080
有空再测试
