### ISSUE TITLE
[kernel]: 当在virtualbox启动时，有机率会出现内存不能为read的错误

### ISSUE THREAD

**Issue by chinanoahli** [EdgelessPE/Edgeless#26]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Maybe it's a hardware incompatible problem?

Yes. I use Edgeless with modern hardware.

### Edgeless Version

4.1.0

### What about alpha release?

Yes. I have tried the latest alpha release.

### What happened?

开机即出现，无需任何操作
![QQ截图20220703220325](https://user-images.githubusercontent.com/10005128/177041175-d35e850c-705c-4e24-8334-7583298e7cc9.png)
![QQ截图20220703220409](https://user-images.githubusercontent.com/10005128/177041181-fb38950b-d64b-4f39-b62b-a61f10458c29.png)

加载了下列插件：
```
Chrome_103.0.5060.66_Cno（bot）.7z
Everything_1.4.1.1017_Cno（bot）.7z
dotNetFXs-3.0-4.5_1.0.0.1_Oxygen.7z
netCoreDesktopRuntime_3.1.5_Oxygen.7z
微软常用运行库_22.04.09_泉水叮咚.7z
搜狗拼音_12.1.0.0_Cno（bot）.7z
```

**Comment by Cnotech** [comment]
https://wiki.edgeless.top/v2/faq/someerror.html
