### ISSUE TITLE
[hub]: 

### ISSUE THREAD

**Issue by CharlesHim** [EdgelessPE/Edgeless#28]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Ventoy Wiki

- [X] This is not a Ventoy self issue or a hardware incompatible problem.

### Edgeless Hub Version

2.27

### What about the latest release?

- [X] Yes. That still happens.

### Which version of Windows are you using?

Windows 11

### What happened?

无论safe boot是否在bios中禁用，启动时始终提示应关闭safeboot，并跳过pe直接进入windows。
已确认U盘硬件正常，引导顺序无误，并尝试重新制作pe启动盘。

**Comment by Cnotech** [comment]
**This is a Ventoy self issue**

**Comment by Cnotech** [comment]
安全启动的问题都仅仅与Ventoy有关，已经在文档里面写的很清楚了，发布issue之前请认真阅读Edgeless Wiki和issue模板中的相关提示，而不是不假思索地随手勾选相应的复选框

**Comment by Cnotech** [comment]
你可以检查一下是不是制作时勾选了Ventoy的安全启动模式支持，这个模式并非所有设备都能很好的兼容，Edgeless给出的官方建议是不启用这个功能。

此外，如果在bios关闭了安全启动而你的设备依旧在检查安全启动密钥则需要考虑一下是不是你控制的选项有问题，或者主板bios存在逻辑漏洞。
