### ISSUE TITLE
一些可以实现的建议

### ISSUE THREAD

**Issue by SteveZMTstudios** [EdgelessPE/Edgeless#29]
1.修改一下ventoy引导启动的背景
实现方案：命令行允许访问VTOYEFI分区，在ventoy\theme中替换background.png
2.设定ventoy默认启动镜像选项
方案：修改ventoy.json(具体方法见ventoy官网）
3.镜像引导密码
原因：可以防止误开引导镜像

我正考虑集成一些这些功能。并把他们做成可以包入edgeless HUB的executable file

edgeless是国内最优秀的pe镜像，可能没有之一。

zzhzcuid@outlook.com

**Comment by Cnotech** [comment]
感谢你的建议，不过这些涉及的更改对象为Ventoy而非Edgeless本体，据我的了解这些功能都可以使用Ventoy配置实现。

因为隶属于两个不同的项目，Edgeless Hub不方便直接介入对Ventoy配置的修改，因此不考虑在Hub内实现这些功能。如果有能力可以创建一个Ventoy的第三方配置客户端。
