### ISSUE TITLE
[kernel]: X盘的空间

### ISSUE THREAD

**Issue by bixtx** [EdgelessPE/Edgeless#30]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Maybe it's a hardware incompatible problem?

No. I don't know Edgeless Project won't care about compatible.

### Edgeless Version

4.1.0

### What about alpha release?

No. I don't know where to get alpha release.

### What happened?

我在`U盘:/Edgeless/Resource`目录放置了很多插件包，导致X盘被塞满了，一些插件无法运行。求问怎么增加X盘的大小？

**Comment by bixtx** [comment]
X盘只有8GB的空间，是真的不够用啊！

**Comment by Cnotech** [comment]
按需取用插件包，并将不需要自动加载的插件后缀改为`.7zf`，否则即使内存放得下每次启动的时间也会很长。 出于兼容性考虑不会更改X盘的容量。
