### ISSUE TITLE
关于部分未提供应用版本的插件包命名方案

### ISSUE THREAD

**Issue by wdw1007** [EdgelessPE/Edgeless#32]
### 问题描述
如 [github.com/haveyouwantto/WindsongLyre-Sim](url)
是一个 HTML 应用
该应用并没有任何版本号

### 相关方案
对于此类应用，命名方案是否可以为
[程序名称-分支名] _ [最新的 commit 的年].[最新的 commit 的月日].[最新的 commit 的时分] _ [打包者]
例如 WindsongLyre-Sim-main_2022.0815.0318_user

**Comment by Cnotech** [comment]
感觉分支名没必要加上了，`WindsongLyre-Sim_2022.0815.0318_user`就可以。或者`WindsongLyre-Sim_1.0.0.0_user`，由打包者维护这个版本号。

**Comment by wdw1007** [comment]
彳亍
