### ISSUE TITLE
[hub]: 安装成功但是无法启动到edgeless

### ISSUE THREAD

**Issue by Gayhub666** [EdgelessPE/Edgeless#33]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Ventoy Wiki

- [X] This is not a Ventoy self issue or a hardware incompatible problem.

### Edgeless Hub Version

2.27

### What about the latest release?

- [X] Yes. That still happens.

### Which version of Windows are you using?

Windows 10

### What happened?

我尝试在一个希捷移动硬盘上安装edgeless，使用ventoy处理硬盘时候一切正常，ventoy没有任何报错，但是安装完成关闭ventoy之后hub显示没有安装ventoy
![image](https://user-images.githubusercontent.com/96622524/184904208-2dbdf946-1f69-46b4-b6b7-1b7aa425fd58.png)
我手动选择盘符之后可以正常完成安装，没有报错
但是进入bios，把这个移动硬盘设置成第一启动顺序之后还是会启动原来的win10系统，没法进入edgeless，就像正常开机一样
我已经按照说明关闭了安全启动，并且确认微pe之类工具能正常使用，电脑是联想拯救者y7000 2020版

**Comment by Gayhub666** [comment]
目前没有找到日志之类的东西，如果有需要我会上传日志

**Comment by Gayhub666** [comment]
刚才重新试了下，安装ventoy时候手动选择gpt分区类型之后虽然hub还是检测不到ventoy已经安装，但是手动选择盘符继续安装之后就可以启动了，建议在这里写个说明，告知用户要是不行的话切换下分区格式

**Comment by Cnotech** [comment]
hub找不到ventoy盘符是个bug，但是现在已经停止维护所以需要等待重构才能解决。感谢你的建议，我们会考虑增加一个tip。

**Comment by ghost** [comment]
有时还会进PE后不加载插件（悲）
我的插件VMware……
