### ISSUE TITLE
[hub]: 制作失败

### ISSUE THREAD

**Issue by fangyuan99** [EdgelessPE/Edgeless#34]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Ventoy Wiki

- [X] This is not a Ventoy self issue or a hardware incompatible problem.

### Edgeless Hub Version

2.26

### What about the latest release?

- [X] Yes. That still happens.

### Which version of Windows are you using?

Windows 10

### What happened?

![image](https://user-images.githubusercontent.com/62874116/188309121-14584343-7eb3-4b71-b7c8-522a362f7a89.png)
# Edgeless Hub Log
>  18:32:46-version 2.26
18:32:46-log 从store中恢复状态-Burn
18:32:46-log {"startedTasks":[false,false,false],"finishedTasks":[false,false,false],"whenReadyUnzip":false,"showExecVentoyButton":false,"showProgress":false,"speed":0.1,"stageLimit":0.3,"selectedVentoyPart":"","ventoyInfo":{"version":"","gid":"","url":"https://pineapple.edgeless.top/api/v2/info/ventoy_addr","fileName":"","ventoyPath":"","pluginName":"ventoy_wimboot.img","finishUnzip":false,"queryUrl":"https://pineapple.edgeless.top/api/v2/info/ventoy_name"},"stepsInfo":{"hasVentoy":false,"step":-1,"stepText":"开始","step3percent":0,"data":[{"title":"下载依赖文件","content":"Edgeless Hub将自动获取最新版Ventoy启动盘制作程序"},{"title":"安装Ventoy","content":"手动点击，将Ventoy安装至您的U盘"},{"title":"部署Edgeless","content":"Edgeless Hub会自动处理启动盘以完成Edgeless的安装"}]}}
18:32:47-log 开始下载依赖-startNesDownload
18:32:47-log 开始下载wim插件-startPluginDownload
18:32:47-log 开始下载ISO-startIsoDownload
18:32:47-log wim插件：文件名=ventoy_wimboot.img gid=8938a185c8f8a52c-startPluginDownload
18:32:47-log 更新ISO信息：文件名=Edgeless_Beta_4.1.0.iso url=https://pineapple.edgeless.top/disk/Socket/Edgeless_Beta_4.1.0.iso version=4.1.0-startIsoDownload
18:32:47-log 获得ventoy的下载地址：https://pineapple.edgeless.top/api/v2/info/ventoy_addr-startVentoyDownload
18:32:47-log ISO下载gid：2fd5cfaaa24ea87c-startIsoDownload
18:32:47-log ventoy信息：文件名=ventoy-1.0.79-windows.zip gid=130c757e327a307f-startVentoyDownload
18:32:48-log Ventoy下载已经完成，发送解压事件unzip-request-Burn_setInterval
18:32:48-log Task0停止，totalLength=15970438 completedLength=15970438-Burn_setInterval
18:32:48-log Task1停止，totalLength=2936832 completedLength=2936832-Burn_setInterval
18:32:48-log Task2停止，totalLength=849051648 completedLength=849051648-Burn_setInterval
18:32:48-log 收到解压完成的回复-unzip_reply_anonymous
18:32:48-log ventoyPathD:\HubCache\Burn\ventoy-1.0.79-unzip_reply_anonymous
18:32:49-log 下载完成，翻页并运行Ventoy
18:32:49-log 调用Ventoy安装程序-execVentoy
18:32:51-log Ventoy安装程序运行结束，调用checkVentoyUDisk-execVentoy
18:32:51-log 校验Ventoy，发送getVentoyDisk事件-checkVentoyUDisk
18:32:51-log 以下为Ventoy日志解析结果-getVentoyDisk_reply
18:32:51-log {}
18:32:51-log 未发现任何设备-getVentoyDisk_reply
18:32:52-log 紧急模式被调用-emergency
18:32:53-log 用户手动选择了盘符：F-selectVentoyPart
18:32:54-log 前往步骤3 this.selectedVentoyPart=F-jumpToStep3
18:32:54-log 翻页并执行step3-jumpToStep3
18:32:54-log 步骤3开始 this.selectedVentoyPart=F-edgelessOperator
18:32:54-log 开始复制ventoy_wimboot插件-edgelessOperator
18:32:54-log 结束复制ventoy_wimboot插件-edgelessOperator
18:32:54-log 开始解包ISO-edgelessOperator
18:32:54-log 发送解包事件unpackISO-request -unpackISO
18:32:59-log 结束解包ISO-edgelessOperator
18:32:59-log 开始复制Edgeless文件夹-edgelessOperator
18:33:8-log 结束复制Edgeless文件夹，计算的写入速度：6.702874834144184-edgelessOperator
18:33:8-log 开始复制boot.wim-edgelessOperator
18:33:8-log 结束复制boot.wim，开始收集文件信息-edgelessOperator
18:33:8-log iso,edgeless,plugin：false,false,false-edgelessOperator
18:33:8-log 向用户报告错误：报错信息： 启动文件缺失：F:\Edgeless_Beta_4.1.0.wim 启动依赖缺失：F:\Edgeless\ Ventoy插件缺失：F:\ventoy\ventoy_wimboot.img-edgelessOperator

**Comment by Cnotech** [comment]
有别的U盘吗，可以尝试换个U盘

**Comment by Cnotech** [comment]
长时间未回复，故关闭
