### ISSUE TITLE
[hub]: 安装完毕，无法启动到pe，黑屏

### ISSUE THREAD

**Issue by k650dg4d2** [EdgelessPE/Edgeless#35]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Ventoy Wiki

- [X] This is not a Ventoy self issue or a hardware incompatible problem.

### Edgeless Hub Version

4.1.0

### What about the latest release?

- [X] Yes. That still happens.

### Which version of Windows are you using?

Windows 10

### What happened?

一切完好，从U盘启动的时候就无法启动了，一直黑屏。电脑型号：k650d-g4d2

**Comment by Cnotech** [comment]
可以在写入Ventoy时尝试取消勾选“安全启动支持”或修改分区类型为“GPT”，或是参考这篇内容：https://wiki.edgeless.top/v2/playground/no-ventoy.html

**Comment by k650dg4d2** [comment]
> 可以在写入Ventoy时尝试取消勾选“安全启动支持”或修改分区类型为“GPT”，或是参考这篇内容：https://wiki.edgeless.top/v2/playground/no-ventoy.html

换成gpt可以进去了，但是加载时间太长了，试了两次，无奈放弃。

**Comment by Cnotech** [comment]
插件放太多了？

**Comment by k650dg4d2** [comment]
> 插件放太多了？

就一个搜狗拼音，不知道咋回事，每次载入时间都特别长

**Comment by Cnotech** [comment]
关联issue #34，启动速度过慢推断由硬件问题导致，此问题视为已解决

**Comment by k650dg4d2** [comment]
> 关联issue #33，启动速度过慢推断由硬件问题导致，此问题视为已解决

找到原因了，是因为我把U盘插在了USB扩展接口上。插到电脑上的USB接口就好了
