### ISSUE TITLE
[hub]: ghost文件无法进行还原

### ISSUE THREAD

**Issue by zuzhilong** [EdgelessPE/Edgeless#37]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Ventoy Wiki

- [X] This is not a Ventoy self issue or a hardware incompatible problem.

### Edgeless Hub Version

微PE工具包_2.1.0.0_Cno.7z

### What about the latest release?

- [X] Yes. That still happens.

### Which version of Windows are you using?

Windows 8 or earlier (No official support)

### What happened?

ghost文件无法进行还原，直接提示还原成功

**Comment by Cnotech** [comment]
我们已经弃用且不会继续关注与ghost还原相关的技术，如仍有需要请使用开始菜单的CGI。所提到的插件包中的内容均搬运自微pe，因此Edgeless官方对其是否能正常使用不负责，你可以自行升级此插件包中的文件然后将更新的版本提交给我们。
