### ISSUE TITLE
无法打开edgeless.top

### ISSUE THREAD

**Issue by taoqixfz** [EdgelessPE/Edgeless#39]
网站怎么打不开了

**Comment by Cnotech** [comment]
今天凌晨的时候DNSPod探针检测到网站宕机，7点又自行恢复。查看了站点面板没有发现异常情况，原因不明。
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/53827731/203006828-dbe2c18b-f26a-44fa-8eea-7d2c65e8538a.png">
