### ISSUE TITLE
[website]: 请问网站问题什么时候能修好？

### ISSUE THREAD

**Issue by zhuzixuan2019241** [EdgelessPE/Edgeless#41]
### What happened?

我用的是移动宽带，无法访问，请问什么时候能修好？因为最近急用，SharePoint的源又不可用。如果短期内无法修复我可能考虑先用别的PE了，等修好后再换回来

**Comment by SevenPlusJun** [comment]
不仅仅是移动宽带的问题，应该是他那边CDN的问题

**Comment by Cnotech** [comment]
近日站点集群维护，现已恢复
