### ISSUE TITLE
[kernel]: 爱国者的U盘可能无法启动Edgeless

### ISSUE THREAD

**Issue by AkarinLiu** [EdgelessPE/Edgeless#42]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Maybe it's a hardware incompatible problem?

Yes. I use Edgeless with modern hardware.

### Edgeless Version

4.1.0

### What about alpha release?

No. I don't know where to get alpha release.

### What happened?

我尝试使用从BIOS启动Edgeless，但是遇上了无法启动的问题，一直卡在白线闪烁画面，型号是aigo U330。

**Comment by Cnotech** [comment]
试试这个：https://wiki.edgeless.top/v2/playground/no-ventoy.html

**Comment by AkarinLiu** [comment]
这个问题已经反馈给[Ventoy](https://github.com/ventoy/Ventoy/issues/2221)了，我使用了EPC大佬的白眼扩容磁盘检测工具，结果U盘没有问题，但是无法正常引导。

**Comment by AkarinLiu** [comment]
顺便一提，我的这台电脑是Acer Aspire 3820TG
