### ISSUE TITLE
已充电，项目挺好的；不过，为什么不做一个赞助名单呢？

### ISSUE THREAD

**Issue by hoochanlon** [EdgelessPE/Edgeless#43]
### What happened?

现在大家的正版意识比以前大有改善，也愿意付费。做一个赞助名单的话，相对来说也能激发些一部分网友的热情。

**Comment by Cnotech** [comment]
点击捐赠二维码就可以看到名单的，或者在文档中查看

**Comment by hoochanlon** [comment]
好的，谢谢。项目已收藏GitHub存档仓库。

发自我的 iPad

在 2023年2月11日，17:10，L0serj3rry ***@***.***> 写道：

﻿

Closed #43<https://github.com/EdgelessPE/Edgeless/issues/43> as completed.
