### ISSUE TITLE
[hub]: 错误：启动盘的文件不完全，启动盘制作失败

### ISSUE THREAD

**Issue by Randark-JMT** [EdgelessPE/Edgeless#44]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Ventoy Wiki

- [X] This is not a Ventoy self issue or a hardware incompatible problem.

### Edgeless Hub Version

2.27

### What about the latest release?

- [X] Yes. That still happens.

### Which version of Windows are you using?

Windows 10

### What happened?

错误：启动盘的文件不完全，启动盘制作失败
报错信息： 启动文件缺失：E:\Edgeless_Beta_4.1.0.wim 启动依赖缺失：E:\Edgeless\

![图片](https://user-images.githubusercontent.com/56223739/221084777-4f158ce1-e277-4a61-94b7-f8ac11fb4990.png)

Logs:
```log
11:25:45-log 未发现任何设备-getVentoyDisk_reply
11:26:23-log 紧急模式被调用-emergency
11:26:24-log 用户手动选择了盘符：E-selectVentoyPart
11:26:25-log 前往步骤3 this.selectedVentoyPart=E-jumpToStep3
11:26:25-log 翻页并执行step3-jumpToStep3
11:26:25-log 步骤3开始 this.selectedVentoyPart=E-edgelessOperator
11:26:25-log 开始复制ventoy_wimboot插件-edgelessOperator
11:26:25-log 结束复制ventoy_wimboot插件-edgelessOperator
11:26:25-log 开始解包ISO-edgelessOperator
11:26:25-log 发送解包事件unpackISO-request -unpackISO
11:26:25-log 结束解包ISO-edgelessOperator
11:26:25-log 开始复制Edgeless文件夹-edgelessOperator
11:26:25-log 结束复制Edgeless文件夹，计算的写入速度：1782.964705882353-edgelessOperator
11:26:25-log 开始复制boot.wim-edgelessOperator
11:26:25-log 结束复制boot.wim，开始收集文件信息-edgelessOperator
11:26:25-log iso,edgeless,plugin：false,false,true-edgelessOperator
11:26:25-log 向用户报告错误：报错信息： 启动文件缺失：E:\Edgeless_Beta_4.1.0.wim 启动依赖缺失：E:\Edgeless\-edgelessOperator
```

**Comment by Cnotech** [comment]
可以尝试更换一下u盘或者手动从iso把这两个文件夹复制进去。hub已经在重构中了。

**Comment by Randark-JMT** [comment]
okok
