### ISSUE TITLE
[hub]: extualIdentity = Microsoft.Windows.SystemCompatible,version="6.0.0.0",type="win32",publicKeyToken="6595b64144ccf1df", processorArchitecture="x86" AssemblyDirectory = C:\Windows\WinSxs

### ISSUE THREAD

**Issue by 12492750** [EdgelessPE/Edgeless#45]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Ventoy Wiki

- [X] This is not a Ventoy self issue or a hardware incompatible problem.

### Edgeless Hub Version

2.27

### What about the latest release?

- [X] Yes. That still happens.

### Which version of Windows are you using?

Windows 11

### What happened?

我在研究edgeless的插件，以便更好的匹配软件，在WindowsPE中我遇到32位的应用程序在PE中报错，按照教程我拷贝了winsxs，system32和syswow64文件，但是报错The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
解析后得到
extualIdentity = Microsoft.Windows.SystemCompatible,version="6.0.0.0",type="win32",publicKeyToken="6595b64144ccf1df", processorArchitecture="x86"AssemblyDirectory = C:\Windows\WinSxs
我不知道哪里出了问题

**Comment by Cnotech** [comment]
为PE适配插件本身是一件比较复杂繁琐的事情，建议在我们的QQ群中寻求帮助。这不属于Edgeless的缺陷，因此关闭此issue。
