### ISSUE TITLE
如何从硬盘启动Edgeless

### ISSUE THREAD

**Issue by laoliuhhh** [EdgelessPE/Edgeless#46]

**Comment by Cnotech** [comment]
如果你正在使用较旧版本的Windows 10，可以在使用u盘启动进入Edgeless后尝试使用”开始菜单-Edgeless服务-写入Edgeless到本地硬盘“，这样做会替换系统原有的WinRE环境为Edgeless。但是在较高版本的10或11系统中此方法已经失效。

或者关闭UEFI启动之后使用EasyBCD添加ISO的引导项，但是这样会极大延长正常系统的启动时间，不推荐。
