### ISSUE TITLE
[website]: 请求撤下或替换链接

### ISSUE THREAD

**Issue by Tim-Paik** [EdgelessPE/Edgeless#47]
### What happened?

https://home.edgeless.top/ 下方友情链接中 Tim_Paik （我）的域名 timpaik.ga 已经无法续费（账号被风控），存在死链风险，并且已经弃用2年多了。
~~新的地址在~~ 好吧没有新的地址，事实证明域名这玩意还是得记着续费才能好好用的，如果想更换的话可以使用 https://tim-paik.github.io/ 或者 https://timpaik.top ，当然您也可以直接把我的链接删掉（毕竟属实没啥好内容）

~~项目开发缺人手的话可以拉我过去当苦力啊~~

另祝项目顺利。

**Comment by Cnotech** [comment]
done
