### ISSUE TITLE
[hub]: Windows 安全中心误报

### ISSUE THREAD

**Issue by wuyuncheng-26** [EdgelessPE/Edgeless#48]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Ventoy Wiki

- [X] This is not a Ventoy self issue or a hardware incompatible problem.

### Edgeless Hub Version

2.27

### What about the latest release?

- [X] Yes. That still happens.

### Which version of Windows are you using?

Windows 11

### What happened?

在制作Edgeless的启动盘时，Windows 安全中心提示电脑受到威胁：在Edgeless Hub缓存目录中的Burn\release\Edgeless\Nes_Inport.7z提示发现Trojan:Win32/Azorult

**Comment by Cnotech** [comment]
请自行解决

**Comment by mcl44** [comment]
> ### Official Wiki
> * [x]  I've checked the official Wiki throughout.
> 
> ### Ventoy Wiki
> * [x]  This is not a Ventoy self issue or a hardware incompatible problem.
> 
> ### Edgeless Hub Version
> 2.27
> 
> ### What about the latest release?
> * [x]  Yes. That still happens.
> 
> ### Which version of Windows are you using?
> Windows 11
> 
> ### What happened?
> 在制作Edgeless的启动盘时，Windows 安全中心提示电脑受到威胁：在Edgeless Hub缓存目录中的Burn\release\Edgeless\Nes_Inport.7z提示发现Trojan:Win32/Azorult

ms是这样的，没办法，自行百度解决吧
