### ISSUE TITLE
给Edgeless的一些建议

### ISSUE THREAD

**Issue by wuyuncheng-26** [EdgelessPE/Edgeless#49]
# 压缩包格式
Edgeless的压缩包都是.7z格式的，比如说Edgeless Hub，但有些人的电脑没有装7-Zip，所以希望压缩包的格式可以改成.zip这种常用的格式。
# 对Ventoy设置的一些支持
有一些Ventoy的设置Edgeless是不支持的，比如说[全局控制插件](https://ventoy.net/cn/plugin_control.html)里的***VTOY_DEFAULT_SEARCH_ROOT***配置，我个人用的是Edgeless Alpha 4.12版本，但当我改了目录之后，Edgeless Hub就检测不到我装了4.12了，只识别到我装了4.10。
# 驱动问题
装不上驱动估计是很多人用PE时遇到的问题，像笔记本电脑就需要手动打很多驱动。希望可以把[添加驱动](https://wiki.edgeless.top/v2/playground/driver.html)这一步加到Edgeless的写入过程中。
# 增加一个清理缓存按钮
Edgeless的缓存里全是一些下载文件，但一般用了一次过后就不会再用了，像我的缓存就占用了2.78GB，所以希望能增加一个清理缓存的功能。
# Edgeless Hub
1. 调主题只支持调侧边栏，希望可以把整个界面都调了。
2. 阅览Wiki界面的大小似乎有点不对劲，希望可以调成全屏。
3. 每次进入内侧界面时都要输入内测码，虽然会保留上次输入的，但还是感觉很不方便。
# Edgeless界面
PE里的图标可不可以改成跟[FirPE](https://firpe.cn/page-247)差不多风格的圆形图标，感觉现在的图标有些不美观。
# 写在最后
感谢Cno以及Edgeless其他开发者和测试人员的辛勤付出，做出了Edgeless这个既可以维护系统，又可以满足生活需求的PE系统，向你们致敬！

**Comment by Cnotech** [comment]
感谢你的建议，不过Edgeless PE本身的维护更新已进入半搁置状态（详见文档的日志），新功能更新和缺陷修复工作会很少，你可以通过为[wimbuilder-component](https://github.com/EdgelessPE/wimbuilder-component)仓库提交PR来实现某些新功能或修复部分缺陷。

回复1：7z已经是通用压缩包标准之一，只要随意安装一个压缩软件就可以打开7z压缩包，不一定需要安装7-Zip来打开；此外，zip也不是一个更佳的解决方案，我们最近正在开发的包管理项目使用了ztsd+tar的自定义解决方案，相比于其他压缩与归档格式在解压速度和压缩率上提升明显；

回复2：确实是这样，Hub并没有加入对于Ventoy高级特性的支持而且已经停止维护了，新Hub的开发由于一些原因也被暂时搁置；不过理论上将4.1.2检测为4.1.0不会影响实际使用（获取内测除外）；

回复3：想法很好，但是我们没有这个能力提供这种服务...此外PE是安装在U盘中的，无法预测将会在哪台电脑上启动，因此实际意义也不大，还是自己动手丰衣足食吧（参考文档制作驱动插件包）；

回复4：确实有这个问题，早期确实想做一键清理功能，但是部分用户会把缓存路径配置成自己的桌面或者下载目录，一键清理时无法区分哪些文件是Hub缓存哪些是用户的文件，因此就只放了个查看缓存目录的按钮；

回复5：见回复2，我们也意识到了这些问题，但是目前没精力实现；

回复6：使用主题包功能（见文档），去网页版下载站可以下载主题包和资源包

**Comment by wuyuncheng-26** [comment]
谢谢Cno的回复！
