### ISSUE TITLE
[issue]: 错误：没有发现Ventoy启动盘

### ISSUE THREAD

**Issue by pgllove** [EdgelessPE/Edgeless#5]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Maybe it's a hardware incompatible problem?

Yes. I use Edgeless with modern hardware.

### Edgeless Version

3.2.0

### What about alpha release?

No. I don't know where to get alpha release.

### What happened?

128gU盘，用分区助手和diskgenius反复尝试删除两个分区重做，总是报找不到ventoy启动盘

**Comment by pgllove** [comment]
用2.02可以

**Comment by Cnotech** [comment]
issue回顾：2.19版本的Hub修复了在Windows 11环境下what-did-ventoy-do的异常抛出问题，猜测此issue也由此问题引起，并且作者长期未回复，故关闭此issue
