### ISSUE TITLE
[kernel]:  我自己修改的AM4 NVMe_CC 的RAID 驱动插件包。望merge。

### ISSUE THREAD

**Issue by gtr3qq** [EdgelessPE/Edgeless#51]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Maybe it's a hardware incompatible problem?

Yes. I use Edgeless with modern hardware.

### Edgeless Version

4.1.0

### What about alpha release?

Yes. I have tried the latest alpha release.

### What happened?

基于AM4RAIDDriver_9.3.0.296_Ran.7z
已经在asus prime x470 认证其可以正确加载NVMe RAID，并且成功在一个RAID1 卷上安装win10。(是的...规避SSD 数据火葬场)

在Edgeless官网找不到任何开发群的信息，故在此打扰。
VER: 9.3.0.296
不常用PE，但Edgeless的高度可定制设计的确令人耳目一新，十分好用，请再接再厉！

[AM4NVMe_RAID_9.3.0.296_GTR3QQ.7z.zip](https://github.com/EdgelessPE/Edgeless/files/11957467/AM4NVMe_RAID_9.3.0.296_GTR3QQ.7z.zip)
![image](https://github.com/EdgelessPE/Edgeless/assets/76813695/8a86de2e-d86d-4acb-bec5-b53064ed4bf5)

**Comment by Cnotech** [comment]
已上架。群在底部的“获取内测”

**Comment by Cnotech** [comment]
不过AM4RAIDDriver_9.3.0.296_Ran.7z 这个插件和你的区别是什么？

**Comment by gtr3qq** [comment]
> 不过AM4RAIDDriver_9.3.0.296_Ran.7z 这个插件和你的区别是什么？

well, 这个驱动会以CC 的方式控制、替换 标准NVMe 设备 驱动，给上层amd raid cfg 驱动传输metadata。。。
为什么不打开来CRC32 一下里面的文件呢？☺

**Comment by gtr3qq** [comment]
驱动都是AMD 提供的，一共有三个，
SATA_RAID
NVMe_CC
NVMe_DID
上一个插件加载的只是sata only。
