### ISSUE TITLE
[kernel]: 卡在edgeless部署

### ISSUE THREAD

**Issue by dddddgz** [EdgelessPE/Edgeless#53]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Maybe it's a hardware incompatible problem?

Yes. I use Edgeless with modern hardware.

### Edgeless Version

2.27

### What about alpha release?

No. I don't know where to get alpha release.

### What happened?

卡在这里
![Snipaste_2023-07-25_15-06-00](https://github.com/EdgelessPE/Edgeless/assets/134162766/51febc6a-4674-4097-aa5c-0878792a84b1)

**Comment by Cnotech** [comment]
可以尝试重试，或者手动写入：https://wiki.edgeless.top/v2/guide/burn_manual.html
