### ISSUE TITLE
Edgeless插入电脑界面异常报错

### ISSUE THREAD

**Issue by renshengx** [EdgelessPE/Edgeless#62]
Ventoy有两个分区，进入分区1，显示如图1，重启进入分区2，显示如图2，都达到不了想要的结果。
![1 1](https://github.com/EdgelessPE/Edgeless/assets/107403232/c0367a22-b4e0-4199-9774-bcb7af62df3d)
![2 1](https://github.com/EdgelessPE/Edgeless/assets/107403232/ac737140-bc64-42f7-84bc-57104d7a178b)

**Comment by Cnotech** [comment]
![image](https://github.com/EdgelessPE/Edgeless/assets/53827731/9ae79e06-1b9a-4a3c-941d-a57ef0781365)

**Comment by mcl44** [comment]
> Ventoy有两个分区，进入分区1，显示如图1，重启进入分区2，显示如图2，都达到不了想要的结果。 ![1 1](https://private-user-images.githubusercontent.com/107403232/323441316-c0367a22-b4e0-4199-9774-bcb7af62df3d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTYxMTgsIm5iZiI6MTcyMzM1NTgxOCwicGF0aCI6Ii8xMDc0MDMyMzIvMzIzNDQxMzE2LWMwMzY3YTIyLWI0ZTAtNDE5OS05Nzc0LWJjYjdhZjYyZGYzZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQwNTU2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWM5OTlkYWEzMWIyM2U3MDhlY2MxY2RhZWEzMTY2OTEzYTgyNWRmYmJkNzlhZmE0NTg4NDRmMzZhOTg0MzFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vOMrzN-orrJrUcr66lO7aDOx4MVUpSK6hVgW1AOh3t0) ![2 1](https://private-user-images.githubusercontent.com/107403232/323441368-ac737140-bc64-42f7-84bc-57104d7a178b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTYxMTgsIm5iZiI6MTcyMzM1NTgxOCwicGF0aCI6Ii8xMDc0MDMyMzIvMzIzNDQxMzY4LWFjNzM3MTQwLWJjNjQtNDJmNy04NGJjLTU3MTA0ZDdhMTc4Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQwNTU2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjY2MjY2OGVmZWQ2MDE2Nzg4OTVmMTdlMTViNzc5YmVkOThhMGFjMmVkZjExNzFmNDA1NGFiOWZmZGY3NGNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7SZQ4BF59xh72eRenW_SDOVNThHiGcBS9X7vUJPAtg0)

ventoy目前已支持安全启动，详情参见ventoy官方文档
