### ISSUE TITLE
[hub]: 无法下载PE，切换镜像源也没用，无法在Hub加载已安装的PE的信息

### ISSUE THREAD

**Issue by NewbieXvwu** [EdgelessPE/Edgeless#7]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Ventoy Wiki

- [X] This is not a Ventoy self issue or a hardware incompatible problem.

### Edgeless Hub Version

2.23

### What about the latest release?

- [X] Yes. That still happens.

### What happened?

无法下载必要的依赖文件，切换镜像源也没用，但网页版可以访问，无法进入Hub内测，提示内测码错误，通过网页版下载的文件安装至U盘后Hub能识别已安装但一直在Loading，无法加载已安装版本等数据
U盘内的Edgeless镜像名称：Edgeless.wim，已创建Edgeless文件夹，可通过Ventoy启动

**Comment by NewbieXvwu** [comment]
![image](https://user-images.githubusercontent.com/87637612/144707910-626ade28-8e7b-457c-bb1b-935cdb0883f4.png)
![image](https://user-images.githubusercontent.com/87637612/144707921-4b1acb3a-6b24-443a-9c7c-bc2a0536765a.png)

**Comment by NewbieXvwu** [comment]
![R@4 ({(`0HT7{Y0BOPB$8IU](https://user-images.githubusercontent.com/87637612/144707938-c25ec05a-299f-4ebd-b361-f29236280ec2.png)

**Comment by Cnotech** [comment]
浙江移动无法连接到菠萝云，已安排服务器供应商前去交涉
